name: Daily Liquidity Update

on:
  schedule:
    - cron: '0 1 * * *'  # 每日台灣時間早上 9 點 (UTC+1)
  workflow_dispatch:

jobs:
  update-liquidity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update SQLite cache
        run: |
          python update_cache.py

      - name: Commit and push updated DB
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add liquidity_cache.db
          git commit -m "Auto update: liquidity cache DB"
          git push
